name: neda_central
description: "North Eastern Darts Association Inc."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <3.99.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_lints: ^6.0.0

  get: ^4.7.3
  http: ^1.6.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.4
  share_plus: ^12.0.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  analyzer: ^6.4.1
  custom_lint: ^0.6.4
  custom_lint_builder: ^0.6.4




flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/features/
    - lib/core/
    - lib/routes/
    - lib/services/
    - lib/core/assets/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/core/assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/core/assets/logo.png"